service: registration-of-taxpayers

plugins:
  - serverless-localstack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  profile: ${opt:profile, self:custom.profile}
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    sqsName: ${self:custom.taxPayerSQS.name}

functions:
  - '${file(src/health.serverless.yml)}'
  - '${file(src/taxpayer/taxpayer.serverless.yml)}'
  - '${file(src/validationTrigger/validationTrigger.serverless.yml)}'

resources:
  Resources:
    TaxPayerDynamo:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: cuit
            AttributeType: S
        KeySchema:
          - AttributeName: cuit
            KeyType: HASH
        
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        
        TableName: taxpayer

    TaxPayerSQS:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: ${self:custom.taxPayerSQS.name}
custom:
  defaultStage: local
  profile: localstack
  localstack:
    debug: true
    stages: [local]
  taxPayerSQS:
    name: sqs-queue-${self:custom.defaultStage}
    url: http://localhost:4566/000000000000/sqs-queue-${self:custom.defaultStage}
