service: registration-of-taxpayers

provider:
  name: aws
  profile: ${opt:profile, self:custom.profile}
  stage: ${opt:stage, self:custom.defaultStage}
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-localstack

custom:
  defaultStage: local
  profile: localstack
  localstack:
    debug: true
    stages: [local]

functions:
  health:
    handler: src/health.health
    events: 
      - http:
          path: health
          method: get